### ISSUE TITLE
Hungarian

### ISSUE THREAD

**Issue by doublex** [LuminosoInsight/wordfreq#40]
Here is a big corpus:
http://mokk.bme.hu/en/resources/webcorpus/

Would it be possible to process more languages?

**Comment by rspeer** [comment]
That's great timing, that you brought this up as we were merging the branch that introduces Hungarian.

That actually looks like a great corpus to add as another source for Hungarian. I'll look into using it in an update.

**Comment by doublex** [comment]
This repository is really great code!
Are there any plans to add even more languages (Czech, Slovak, Vietnamese, ...)?

**Comment by rspeer** [comment]
Thanks so much!

You picked some good languages to ask about. My rule of thumb is that each language needs 3 independent sources of data (now that we take the median frequency across the various lists, having 3 is particularly important). Now that you mention it, it appears that Czech and Slovak could be brought up to that standard right now; I just need to download their Wikipedias, because I already have data for them from OpenSubtitles and extracted from the Common Crawl.

Vietnamese is detected very frequently in the Common Crawl and has a large Wikipedia, but there's no OpenSubtitles list for it, and it doesn't seem to appear enough on Twitter. (Or maybe it doesn't appear with the right diacritics so that cld2 can detect it.) So I only have 2 sources there.

If you know of other sources I should look at, like that Hungarian corpus, let me know. I'll open an issue  for Czech and Slovak.
