### ISSUE TITLE
Frequency lists have high-ranked numbers

### ISSUE THREAD

**Issue by Destaq** [LuminosoInsight/wordfreq#87]
Going through the `top_n_list` in several languages shows numbers such as `00` or `0000` as extremely frequent.

Is this expected behavior? These numbers are clearly as not as common as the library says they are, is there a way to remove these numbers from the function's return so they don't skew the result?

```
>>> top_n_list('en', 30)
['the', 'of', 'to', 'and', 'a', 'in', 'i', 'is', 'that', 'for', 'you', 'it', 'on', '00', 'with', 'was', 'be', 'this', 'as', 'are', 'not', 'have', 'at', 'he', 'by', 'from', 'but', '0000', 'my', 'an']
>>> top_n_list('es', 30)
['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'no', 'se', 'un', 'por', 'del', 'es', 'las', 'con', 'una', 'para', 'lo', 'su', 'al', '00', 'como', 'me', 'más', 'si', 'pero', 'o', '0000', 'te']
>>> top_n_list('it', 30)
['di', 'e', 'che', 'il', 'la', 'in', 'a', 'non', 'un', 'per', 'è', 'del', 'l', 'i', 'una', 'le', 'si', 'della', 'con', 'da', '00', 'sono', 'ma', 'al', 'come', 'ha', 'più', 'dei', 'se', 'nel']
```

**Comment by rspeer** [comment]
This is a peculiar decision we made: multi-digit numbers have their digits replaced with 0 and stand in for all numbers of that length.

The purposes of this are:

- we don't need to have 9,000 different wordlist entries for all different 4-digit numbers
- if you are using wordfreq with word2vec or something based on word2vec, you can replace word2vec's `#` with `0` and get the same vocabulary
- we used `0` instead of `#` so that tokenizers would still see them as numbers

I will look into documenting this better.

For the purpose of iterating words by frequency, I'd suggest filtering out words that contain two or more instances of `0`. (This won't be a false positive on, say, "100", because 100 is already counted as "000".) Or, if you wish, words that contain any digits at all.
